
// This file is automatically generated. Do not edit it directly.
// Import the supabase client from the main library instead
import { supabase as mainClient } from '@/lib/supabase';
import type { Database } from './types';

// Re-export the main client for consistency
export const supabase = mainClient;

// Document usage instructions
// Import the supabase client like this:
// import { supabase } from "@/lib/supabase";
